[tool.poetry]
name = "Bhujanga-AI"
version = "0.1.0"
description = "A Snake-AI Project. Attempt to create a diverse range of game agents."
authors = ["Hrushikesh Pawar <hrushikeshpawar96@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
pygame = "^2.1.2"
tqdm = "^4.64.0"
scipy = { version = "^1.9.0", python = ">=3.10,<3.12" }
seaborn = "^0.11.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
loguru = "^0.6.0"
flake8 = "^4.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
